# API Gateway Configuration
app:
  name: "booking-tickets-api-gateway"
  version: "1.0.0"
  environment: "development" # development, staging, production

# Server Configuration
server:
  http:
    host: "0.0.0.0"
    port: 8080
    read_timeout: "30s"
    write_timeout: "30s"
    idle_timeout: "60s"
    graceful_shutdown_timeout: "30s"

# JWT Configuration
jwt:
  secret_key: "your-secret-key-change-in-production-super-secure-32-chars-minimum-2024"

# Redis Configuration (for rate limiting)
redis:
  enabled: true
  host: "localhost"
  port: 6379
  db: 0
  # Token Bucket Rate Limiting Configuration
  token_bucket:
    capacity: 100           # Maximum number of tokens in the bucket
    refill_rate: 1.67       # Tokens per second (100 tokens per minute)
    refill_interval: "1m"   # How often to refill tokens

# Services Configuration
services:
  user_service:
    name: "user-service"
    host: "localhost"
    port: 50051
    grpc:
      keepalive_time: "30s"
      keepalive_timeout: "5s"
      keepalive_permit_without_stream: true
  
  order_service:
    name: "order-service"
    host: "localhost"
    port: 50052
    grpc:
      keepalive_time: "30s"
      keepalive_timeout: "5s"
      keepalive_permit_without_stream: true
